### ISSUE TITLE
Feature request: Server side rendering

### ISSUE THREAD

**Issue by Immortalin** [idom-team/idom#296]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when the page takes time to load, especially when the widgets are big.

**Describe the solution you'd like**
Server side rendering like those used by Gatsby and Next.js.

**Describe alternatives you've considered**
N/A
**Additional context**
Rehydrating the websocket connection will probably require custom code. SSR will most likely need node.js as a dependency.

**Comment by rmorshea** [comment]
@Immortalin I'm definitely open to this since it would help to address questions [like this](https://twitter.com/MarcSkovMadsen/status/1363447679179780097). However, for the moment I'm both under informed on the topic and over committed to other work.

Unless I can find some help on this one, I'll have to finish up what I've already promised to do with IDOM (as well as fix bugs) and then educated myself about Gatsby/Next.js.

Perhaps an intermediate solution to loading times would be to figure out some clever compression techniques to reduce the dependence on network latency?

**Comment by Archmonger** [comment]
> @Immortalin I'm definitely open to this since it would help to address questions [like this](https://twitter.com/MarcSkovMadsen/status/1363447679179780097). However, for the moment I'm both under informed on the topic and over committed to other work.
> 
> Unless I can find some help on this one, I'll have to finish up what I've already promised to do with IDOM (as well as fix bugs) and then educated myself about Gatsby/Next.js.
> 
> Perhaps an intermediate solution to loading times would be to figure out some clever compression techniques to reduce the dependence on network latency?

The simplest SSR method would involve rendering any new DOM components as a HTML string and pushing them into the `innerHTML` of the component selector.

**Comment by Archmonger** [comment]
@rmorshea Might be worth moving all feature requests to GH Discussions so people can vote on them.
