### ISSUE TITLE
Add support for passing a React component as attribute of another

### ISSUE THREAD

**Issue by sadruddin** [idom-team/idom#350]
Some react libraries allow the use of components as attributes, e.g. in material-ui
```jsx
<Input endAdornment={<InputAdornment position="end">Kg</InputAdornment>}/>
```
Currently, idom doesn't support the usage of such attributes, throws an exception on the client side when I use the following
```python
mui.Input({'endAdornment': mui.InputAdornment({'position': 'end'}, 'Kg')})
```
After looking at the code, it looks like a simple fix would be to add the code below to the elementAttributes function in the index.js of the react client codebase

```javascript
Object.keys(attributes).forEach((attrName) => {
  if (attributes[attrName].tagName) {
    attributes[attrName] = html`<${Element} model=${attributes[attrName]}/>`;
  }
});
````
It seems to work in that instance, is it that simple or am I missing something more nuanced?

**Comment by rmorshea** [comment]
I think something like that would solve the problem. However I don't think this belongs in the core IDOM framework for a couple reasons:

1. I'm not aware of any other React component frameworks that do this.
2. This approach doesn't work in all use cases, even within Material UI - custom themes being one example I'm aware of.
3. Implementing this sets up the expectation that IDOM allows you to use React components exactly as you would in JS.

What I'm trying to get at is that, because IDOM isn't transpiling Python to Javascript, the framework will always be limited in one way or another. In my view, the best way to work around that is to narrow the scope of what IDOM delivers on, but give people escape hatches that will allow them to solve a wider variety of problems. Thus, IDOM should focus one being good at state and layout synchronization between the server and the client, while integrations with specific JS packages ought to be solved with the escape hatch of [Custom Components](https://github.com/idom-team/idom-react-component-cookiecutter).

For now, Custom Components are an area of the framework that needs some work, and will probably undergo some change in the near future. But once that's been sorted out, I can foresee a clean, self contained, and `pip` installable `idom-mui` package that implements some version of the solution you proposed above, but also allows you to work with other more specialized parts of the MUI ecosystem (e.g. custom themes) with relative ease.

**Comment by rmorshea** [comment]
I think I might be able to give you a short term hack that implements your solution in a custom component similar to the [one from the docs](https://idom-docs.herokuapp.com/docs/javascript-components.html#import-javascript-bundles) that just uses a single `.js` file rather than the whole component template repository linked above. The solution will probably break once I make changes to the custom component API, but it should work until then.

**Comment by rmorshea** [comment]
Another short-term solution to nicely styled content with IDOM would be to user something like [TailWindCSS](https://tailwindcss.com/)

**Comment by rmorshea** [comment]
I'm going to close this for now. I don't foresee that this will be implemented any time soon. It can be re-opened at a later date if needed.

**Comment by brentbaum** [comment]
@rmorshea What's your reasoning for the following statement?

> Implementing this sets up the expectation that IDOM allows you to use React components exactly as you would in JS.

Components as props is a fairly common pattern in React land as it solves the "customize multiple parts of a child's render without adding a million booleans" problem. For example, a `Page` component could expose three props, `renderHeader`, `renderBody,` and `renderFooter` and leave it to the parent to decide what's rendered in all three areas.

I'm running into this issue in a couple places; it's fine to not have this ability but it leads to some friction.

**Comment by rmorshea** [comment]
I hadn't considered that use case. I don't know when I'll have time to get to this, but I'm going to open this again and re-consider.

**Comment by rmorshea** [comment]
@brentbaum and to be clear, this works fine on the Python side. It's just that you can't pass components declared in Python to a custom component implemented in Javascript.

**Comment by brentbaum** [comment]
@rmorshea Thanks for the clarification; turns out all my use cases are passing python components as props to python components. I took a deeper look and providing more `key` attributes to the components passed as props fixed my bugs.
